spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
    driverClassName:
    initialization-mode: always
  jpa:
    generte-ddl : false
    hibernate:
      ddl-auto: none
      temp:
        use_jdbc_metadata_defaults: false
    show_sql: true
    database-platform : org.hibernate.dialect.PostgreSQL95Dialect

app:
  url: https://ekart-books-zonee.herokuapp.com/